name: lcov_parser
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  path: ^1.7.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.5

