name: lcov_parser
description: A simple command-line application. With this package you will get a list of records of lcov.info file.
version: 0.1.0
homepage: https://github.com/eliasreis54/lcov_parser

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  path: ^1.7.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.5

